"""Video Studio — verified web audit + default 90s walkthrough project.

ISOLATED MODULE. Read-only source-of-truth data derived from a real audit of the
AZURIS app (routes in App.tsx, nav in Header/AdminLayout, pages + i18n labels).
No business logic, no coupling to frozen collections. Nothing here mutates the
existing app; it only describes it for the walkthrough generator.
"""

from __future__ import annotations

# --------------------------------------------------------------------------- #
# PHASE 1 — WEB AUDIT (pages + navigation, verified against the real app)      #
# --------------------------------------------------------------------------- #

PAGES = [
    {"group": "Publik", "name": "Beranda", "route": "/", "auth": False,
     "summary": "Hero 3 slide, empat pilar batu, verifikasi, proses, keunggulan, standar, legalitas, keanggotaan, kontak."},
    {"group": "Publik", "name": "Verifikasi Sertifikat", "route": "/#verification", "auth": False,
     "summary": "Form nomor sertifikat + kode keamanan, atau resolusi QR, menampilkan pratinjau sertifikat resmi."},
    {"group": "Publik", "name": "Proses Sertifikasi", "route": "/#proses", "auth": False,
     "summary": "Lima langkah: pendaftaran, pemeriksaan, dokumentasi, penerbitan, verifikasi digital."},
    {"group": "Publik", "name": "Legalitas", "route": "/legalitas", "auth": False,
     "summary": "Dokumen legalitas resmi (state kosong bila belum dipublikasikan) + komitmen & disclaimer."},
    {"group": "Publik", "name": "Tentang", "route": "/about", "auth": False,
     "summary": "Profil dan positioning institusi gemologi."},
    {"group": "Publik", "name": "Kontak", "route": "/contact", "auth": False,
     "summary": "Kontak resmi dengan tombol WhatsApp bisnis."},
    {"group": "Publik", "name": "Verifikasi Keanggotaan", "route": "/membership", "auth": False,
     "summary": "Portal verifikasi kartu anggota via token; identitas tersamar tanpa data pribadi."},
    {"group": "Auth", "name": "Login Admin", "route": "/login", "auth": False,
     "summary": "Autentikasi admin JWT berbasis peran (RBAC)."},
    {"group": "Admin", "name": "Dashboard", "route": "/admin/dashboard", "auth": True,
     "summary": "Analitik teragregasi aman-privasi: total data, tren verifikasi 14 hari, rincian status, nomor sertifikat berikutnya."},
    {"group": "Admin", "name": "Sertifikat", "route": "/admin/certificates", "auth": True,
     "summary": "Buat data batu, terbitkan sertifikat bernomor unik, kode keamanan sekali pakai, QR, PDF A6, contoh sertifikat, cabut."},
    {"group": "Admin", "name": "Pelanggan", "route": "/admin/customers", "auth": True,
     "summary": "CRUD data pemilik batu; pencatatan persetujuan privasi; kontak tidak pernah publik."},
    {"group": "Admin", "name": "Batu Mulia", "route": "/admin/gemstones", "auth": True,
     "summary": "Katalog batu mulia — status siklus, media/foto, pencarian."},
    {"group": "Admin", "name": "Perhiasan", "route": "/admin/jewelry", "auth": True,
     "summary": "Perhiasan yang tersusun dari satu atau lebih batu mulia."},
    {"group": "Admin", "name": "Garansi", "route": "/admin/warranties", "auth": True,
     "summary": "Garansi per batu — masa berlaku, status, dan versi (terbit ulang)."},
    {"group": "Admin", "name": "Kepemilikan", "route": "/admin/ownership", "auth": True,
     "summary": "Tetapkan pemilik awal + alur transfer tercatat; hanya transfer selesai yang mengubah kepemilikan."},
    {"group": "Admin", "name": "Kartu Anggota", "route": "/admin/membership", "auth": True,
     "summary": "Terbitkan kartu anggota premium; kartu digital depan/belakang + QR verifikasi; identitas tersamar."},
    {"group": "Admin", "name": "Legalitas", "route": "/admin/legalitas", "auth": True,
     "summary": "Kelola & publikasikan kredensial/dokumen legalitas yang tampil di publik."},
    {"group": "Admin", "name": "Visual & Konten", "route": "/admin/visuals", "auth": True,
     "summary": "CMS visual: gambar login, proses, keanggotaan beranda, background dashboard/login/beranda, foto batu."},
    {"group": "Admin", "name": "Pengaturan", "route": "/admin/settings", "auth": True,
     "summary": "Nomor WhatsApp bisnis untuk seluruh tombol kontak publik."},
]

PUBLIC_NAV = ["Beranda", "Verifikasi", "Proses", "Legalitas", "Tentang", "Kontak", "Login"]
ADMIN_NAV = ["Dashboard", "Legalitas", "Sertifikat", "Pelanggan", "Batu Mulia", "Perhiasan",
             "Garansi", "Kepemilikan", "Kartu Anggota", "Visual & Konten", "Pengaturan"]

# --------------------------------------------------------------------------- #
# PHASE 2 — FEATURE MAP (feature / location / function / benefit / action)     #
# --------------------------------------------------------------------------- #

FEATURE_MAP = [
    {"id": "f1", "feature": "Beranda Institusi", "route": "/",
     "function": "Presentasi institusi gemologi + hero tiga slide (empat pilar, berlian & rubi, safir & zamrud).",
     "benefit": "Penonton langsung paham ini platform gemologi tepercaya.",
     "visual_action": "Tampil hero + scroll halus.", "priority": "P0"},
    {"id": "f2", "feature": "Verifikasi Sertifikat Publik", "route": "/#verification",
     "function": "Verifikasi keaslian via nomor sertifikat + kode keamanan atau pemindaian QR; menampilkan pratinjau sertifikat.",
     "benefit": "Siapa pun bisa memastikan keaslian sertifikat secara instan.",
     "visual_action": "Isi nomor + kode, klik Verifikasi.", "priority": "P0"},
    {"id": "f3", "feature": "Proses Sertifikasi", "route": "/#proses",
     "function": "Menjelaskan lima langkah alur pemeriksaan hingga verifikasi digital.",
     "benefit": "Membangun kepercayaan lewat proses transparan.",
     "visual_action": "Scroll melewati lima kartu langkah.", "priority": "P1"},
    {"id": "f4", "feature": "Keunggulan & Standar", "route": "/",
     "function": "Bagian 'Mengapa Azuris' + standar pemeriksaan gemologi.",
     "benefit": "Menegaskan kualitas dan objektivitas pemeriksaan.",
     "visual_action": "Scroll bagian keunggulan & standar.", "priority": "P2"},
    {"id": "f5", "feature": "Legalitas Publik", "route": "/legalitas",
     "function": "Menampilkan dokumen legalitas resmi + komitmen & disclaimer.",
     "benefit": "Kredibilitas hukum yang dapat dilihat publik.",
     "visual_action": "Buka halaman Legalitas.", "priority": "P1"},
    {"id": "f6", "feature": "Kontak WhatsApp", "route": "/contact",
     "function": "Tombol kontak WhatsApp bisnis resmi dari pengaturan terpusat.",
     "benefit": "Jalur komunikasi langsung dan mudah.",
     "visual_action": "Sorot tombol WhatsApp.", "priority": "P2"},
    {"id": "f7", "feature": "Verifikasi Keanggotaan", "route": "/membership",
     "function": "Portal publik memverifikasi kartu anggota via token; identitas tersamar.",
     "benefit": "Keaslian keanggotaan tanpa membocorkan data pribadi.",
     "visual_action": "Buka portal /membership.", "priority": "P1"},
    {"id": "f8", "feature": "Login Admin (RBAC)", "route": "/login",
     "function": "Autentikasi JWT berbasis peran untuk tim admin.",
     "benefit": "Akses aman sesuai peran.",
     "visual_action": "Login → masuk dashboard (kredensial tidak ditampilkan).", "priority": "P0"},
    {"id": "f9", "feature": "Dashboard Analitik", "route": "/admin/dashboard",
     "function": "Ringkasan aman-privasi: total data, tren verifikasi, rincian status, nomor sertifikat berikutnya.",
     "benefit": "Pantau operasional dalam satu layar.",
     "visual_action": "Sorot kartu metrik + grafik tren.", "priority": "P0"},
    {"id": "f10", "feature": "Penerbitan Sertifikat", "route": "/admin/certificates",
     "function": "Catat data batu, terbitkan sertifikat bernomor unik, kode keamanan sekali pakai, QR, dan PDF A6.",
     "benefit": "Alur sertifikasi lengkap dari data hingga dokumen cetak.",
     "visual_action": "Isi form, klik Terbitkan, tampil kode + QR, unduh PDF.", "priority": "P0"},
    {"id": "f11", "feature": "Contoh Sertifikat (Demo)", "route": "/admin/certificates",
     "function": "Pratinjau desain sertifikat berwatermark DEMO tanpa menyimpan data.",
     "benefit": "Lihat desain akhir tanpa menerbitkan sertifikat asli.",
     "visual_action": "Klik 'Lihat Contoh Sertifikat', modal terbuka.", "priority": "P2"},
    {"id": "f12", "feature": "Pelanggan", "route": "/admin/customers",
     "function": "Kelola data pemilik dengan pencatatan persetujuan privasi.",
     "benefit": "Registri pemilik rapi dan patuh privasi.",
     "visual_action": "Tampil daftar + form tambah pelanggan.", "priority": "P1"},
    {"id": "f13", "feature": "Batu Mulia & Media", "route": "/admin/gemstones",
     "function": "Katalog batu mulia — status siklus, media/foto, pencarian.",
     "benefit": "Data batu terstruktur siap disertifikasi.",
     "visual_action": "Tampil katalog + kontrol status/media.", "priority": "P1"},
    {"id": "f14", "feature": "Perhiasan", "route": "/admin/jewelry",
     "function": "Perhiasan yang tersusun dari satu atau lebih batu mulia.",
     "benefit": "Dokumentasi perhiasan yang tertaut ke batu.",
     "visual_action": "Tampil daftar perhiasan.", "priority": "P2"},
    {"id": "f15", "feature": "Garansi", "route": "/admin/warranties",
     "function": "Garansi per batu — masa berlaku, status, versi (terbit ulang).",
     "benefit": "Jaminan yang terlacak dan berversi.",
     "visual_action": "Tampil daftar garansi + form.", "priority": "P1"},
    {"id": "f16", "feature": "Kepemilikan & Transfer", "route": "/admin/ownership",
     "function": "Tetapkan pemilik awal + alur transfer tercatat; kode keamanan dirotasi saat transfer selesai.",
     "benefit": "Riwayat kepemilikan tepercaya dan tak dapat dimanipulasi.",
     "visual_action": "Muat batu, tampil pemilik + riwayat transfer.", "priority": "P1"},
    {"id": "f17", "feature": "Kartu Anggota Digital", "route": "/admin/membership",
     "function": "Terbitkan kartu anggota premium; kartu digital depan/belakang + QR verifikasi; identitas tersamar.",
     "benefit": "Identitas keanggotaan modern yang dapat diverifikasi.",
     "visual_action": "Buka modal kartu digital (depan/belakang + QR).", "priority": "P1"},
    {"id": "f18", "feature": "Legalitas Admin", "route": "/admin/legalitas",
     "function": "Kelola & publikasikan kredensial/dokumen legalitas publik.",
     "benefit": "Kontrol penuh atas konten legalitas resmi.",
     "visual_action": "Tampil daftar kredensial + tombol Publikasikan.", "priority": "P2"},
    {"id": "f19", "feature": "CMS Visual & Konten", "route": "/admin/visuals",
     "function": "Atur gambar login/proses/keanggotaan, background dashboard/login/beranda, dan foto batu beranda.",
     "benefit": "Ubah tampilan publik tanpa menyentuh kode.",
     "visual_action": "Tampil kontrol visual + pratinjau langsung.", "priority": "P2"},
    {"id": "f20", "feature": "Pengaturan Kontak", "route": "/admin/settings",
     "function": "Nomor WhatsApp bisnis untuk seluruh tombol kontak publik.",
     "benefit": "Satu sumber kontak untuk seluruh situs.",
     "visual_action": "Tampil form nomor WhatsApp.", "priority": "P2"},
]

# --------------------------------------------------------------------------- #
# PHASE 3 — 90s CONTENT BLUEPRINT                                              #
# --------------------------------------------------------------------------- #

BLUEPRINT = [
    {"segment": "HOOK", "start": 0, "end": 5,
     "goal": "Kalimat pembuka yang langsung menyampaikan value utama."},
    {"segment": "WHAT IS THIS", "start": 5, "end": 12,
     "goal": "Jelaskan singkat apa produk ini dan siapa penggunanya."},
    {"segment": "FEATURE WALKTHROUGH", "start": 12, "end": 72,
     "goal": "Tunjukkan seluruh fitur nyata, dikelompokkan per workflow."},
    {"segment": "KEY BENEFIT / SUMMARY", "start": 72, "end": 83,
     "goal": "Rangkai semua fitur menjadi satu workflow."},
    {"segment": "CTA", "start": 83, "end": 90,
     "goal": "Ajakan jelas dan singkat."},
]

# --------------------------------------------------------------------------- #
# PHASE 4/5 — SCRIPT + SCENE TIMELINE (Bahasa Indonesia, ~213 words / 90s)     #
# --------------------------------------------------------------------------- #

def _scene(idx, seg, start, end, narration, visual, action, feature, benefit, route, targets, covers):
    return {
        "id": f"scene-{idx:02d}", "index": idx, "segment": seg,
        "start": float(start), "end": float(end),
        "narration": narration, "subtitle": narration,
        "visual": visual, "action": action, "feature": feature, "benefit": benefit,
        "route": route, "record_targets": targets, "covers": covers,
        "status": "draft",
    }


DEFAULT_SCENES = [
    _scene(1, "HOOK", 0, 5,
           "Punya batu mulia berharga? Pastikan keasliannya lewat sertifikasi digital dari Azuris.",
           "Beranda — hero slide berlian dengan logo Azuris.",
           "Tampil hero, zoom-in ringan ke logo & judul.",
           "Beranda Institusi", "Menarik perhatian dengan value utama.",
           "/", ["hero-logo", "home-hero"], ["f1"]),
    _scene(2, "WHAT IS THIS", 5, 12,
           "Azuris Gemological adalah platform pemeriksaan, dokumentasi, dan verifikasi batu mulia profesional, lengkap dengan panel admin untuk seluruh alur kerja.",
           "Scroll beranda (empat pilar & proses) lalu kilas dashboard admin.",
           "Scroll halus di beranda, transisi cepat ke dashboard.",
           "Overview Produk", "Penonton paham produk & penggunanya.",
           "/", ["home-page", "admin-dashboard"], ["f1"]),
    _scene(3, "FEATURE WALKTHROUGH", 12, 20,
           "Pengunjung bisa langsung memverifikasi keaslian. Masukkan nomor sertifikat dan kode keamanan, atau pindai QR, dan pratinjau sertifikat resmi tampil seketika.",
           "Bagian Verifikasi di beranda.",
           "Kursor mengisi nomor + kode, klik Verifikasi.",
           "Verifikasi Sertifikat Publik", "Keaslian dapat dicek instan oleh siapa pun.",
           "/#verification", ["verify-section", "verify-cert-input", "verify-submit"], ["f2"]),
    _scene(4, "FEATURE WALKTHROUGH", 20, 27,
           "Halaman publik menjelaskan lima langkah proses sertifikasi, standar pemeriksaan, legalitas resmi, hingga kontak langsung via WhatsApp.",
           "Scroll proses → standar → legalitas teaser → kontak; buka /legalitas sekilas.",
           "Scroll berurutan, sorot tombol WhatsApp, buka halaman Legalitas.",
           "Proses, Standar, Legalitas & Kontak", "Transparansi & kredibilitas institusi.",
           "/", ["home-process", "home-standards", "legality-teaser"], ["f3", "f4", "f5", "f6"]),
    _scene(5, "FEATURE WALKTHROUGH", 27, 33,
           "Keanggotaan Azuris pun dapat diverifikasi publik; identitas anggota tampil aman tanpa data pribadi.",
           "Bagian keanggotaan beranda → buka portal /membership.",
           "Klik CTA keanggotaan, portal verifikasi terbuka.",
           "Verifikasi Keanggotaan", "Verifikasi aman tanpa membocorkan data pribadi.",
           "/membership", ["home-membership", "home-membership-cta"], ["f7"]),
    _scene(6, "FEATURE WALKTHROUGH", 33, 38,
           "Di sisi admin, tim masuk dengan aman lewat autentikasi berbasis peran.",
           "Halaman login admin, lalu masuk ke dashboard.",
           "Isi login (kredensial tidak ditampilkan), submit, dashboard muncul.",
           "Login Admin (RBAC)", "Akses aman sesuai peran.",
           "/login", ["login-form", "login-submit"], ["f8"]),
    _scene(7, "FEATURE WALKTHROUGH", 38, 45,
           "Dasbor menyajikan ringkasan aman-privasi: total data, tren verifikasi, rincian status, dan nomor sertifikat berikutnya secara otomatis.",
           "Dashboard: kartu metrik, grafik tren verifikasi, bar status, panel nomor sertifikat.",
           "Sorot kartu metrik lalu grafik tren.",
           "Dashboard Analitik", "Pantau operasional dalam satu layar.",
           "/admin/dashboard", ["dash-metrics", "dash-verify-chart"], ["f9"]),
    _scene(8, "FEATURE WALKTHROUGH", 45, 55,
           "Inti platform: penerbitan sertifikat. Catat data batu, terbitkan nomor unik, lalu dapatkan kode keamanan sekali pakai, kode QR, dan PDF A6 siap cetak, bahkan contoh sertifikatnya.",
           "Halaman Sertifikat: form data batu, tombol Terbitkan, tampil kode + QR, Unduh PDF, modal Contoh Sertifikat.",
           "Isi form, klik Terbitkan, sorot kode+QR, klik Unduh PDF lalu Lihat Contoh Sertifikat.",
           "Penerbitan Sertifikat + Demo", "Alur sertifikasi lengkap hingga dokumen cetak.",
           "/admin/certificates", ["cert-issue-btn", "cert-demo-preview-btn"], ["f10", "f11"]),
    _scene(9, "FEATURE WALKTHROUGH", 55, 61,
           "Kelola katalog batu beserta media dan status, susun perhiasan, dan simpan data pelanggan dengan persetujuan privasi.",
           "Montase cepat: Batu Mulia → Perhiasan → Pelanggan.",
           "Transisi antar halaman, sorot elemen kunci tiap halaman.",
           "Katalog Batu, Perhiasan & Pelanggan", "Data operasional terstruktur.",
           "/admin/gemstones", ["admin-nav-gemstones", "admin-nav-jewelry", "admin-nav-customers"], ["f12", "f13", "f14"]),
    _scene(10, "FEATURE WALKTHROUGH", 61, 67,
           "Tambahkan garansi berversi, alur transfer kepemilikan yang tercatat, dan kartu anggota digital lengkap dengan QR.",
           "Montase cepat: Garansi → Kepemilikan → Kartu Anggota (modal kartu digital).",
           "Transisi antar halaman, buka modal kartu anggota di akhir.",
           "Garansi, Kepemilikan & Kartu Anggota", "Layanan pasca-sertifikasi lengkap.",
           "/admin/warranties", ["admin-nav-warranties", "admin-nav-ownership", "admin-nav-membership"], ["f15", "f16", "f17"]),
    _scene(11, "FEATURE WALKTHROUGH", 67, 72,
           "Terakhir, atur tampilan publik lewat CMS visual, ubah kontak WhatsApp, dan publikasikan legalitas.",
           "Montase cepat: Visual & Konten → Pengaturan → Legalitas admin.",
           "Transisi antar halaman, sorot kontrol utama tiap halaman.",
           "CMS Visual, Pengaturan & Legalitas Admin", "Kontrol konten tanpa menyentuh kode.",
           "/admin/visuals", ["admin-nav-visuals", "admin-nav-settings", "admin-nav-legality"], ["f19", "f20", "f18"]),
    _scene(12, "KEY BENEFIT / SUMMARY", 72, 83,
           "Dari verifikasi publik, penerbitan sertifikat, hingga kepemilikan dan keanggotaan, semua alur gemologi berjalan dalam satu sistem yang rapi, aman, dan dapat diverifikasi.",
           "Montase cepat beberapa fitur utama (beranda, verifikasi, sertifikat, kartu anggota).",
           "Potongan cepat berirama antar fitur utama.",
           "Ringkasan Workflow", "Menghubungkan semua fitur menjadi satu alur.",
           "/", ["home-page"], []),
    _scene(13, "CTA", 83, 90,
           "Azuris Gemological, sertifikasi batu mulia yang tepercaya. Verifikasi sertifikat Anda sekarang di situs kami.",
           "Beranda hero + logo Azuris sebagai penutup kuat.",
           "Tahan pada hero + logo, teks CTA muncul.",
           "Call To Action", "Ajakan verifikasi yang jelas dan singkat.",
           "/", ["hero-logo"], ["f1"]),
]


def default_project() -> dict:
    return {
        "_id": "default",
        "title": "AZURIS — Product Walkthrough (TikTok 9:16, 90s)",
        "language": "id",
        "target": {"platform": "TikTok", "aspect": "9:16", "width": 1080,
                   "height": 1920, "duration_sec": 90, "voice": "OpenAI TTS (id)"},
        "blueprint": BLUEPRINT,
        "scenes": DEFAULT_SCENES,
        "phase": "A",
        "version": 1,
    }
