import * as React from "react";
import { DownloadSimple, Eye, Printer } from "@phosphor-icons/react";
import { apiFetch, apiJson } from "@/lib/api";

interface Certificate { uuid:string; certificate_number:string; gemstone_id:string; gemstone_name:string; status:string; version:number; issued_at:string; }
const asset=(c:Certificate,kind:"pdf"|"card")=>`/api/admin/certificates/${c.uuid}/${kind}`;

export default function CertificatesPage(){
  const [items,setItems]=React.useState<Certificate[]>([]),[preview,setPreview]=React.useState<Certificate|null>(null),[previewUrl,setPreviewUrl]=React.useState(""),[tab,setTab]=React.useState<"pdf"|"card">("pdf");
  React.useEffect(()=>{void apiJson<{items:Certificate[]}>("/api/admin/certificates").then(({items:records})=>setItems(records||[]));},[]); // eslint-disable-line react-hooks/exhaustive-deps
  React.useEffect(()=>()=>{if(previewUrl)URL.revokeObjectURL(previewUrl);},[previewUrl]);
  const fetchPdf=async(c:Certificate,kind:"pdf"|"card")=>{const r=await apiFetch(asset(c,kind));if(!r.ok)throw new Error(await r.text());return r.blob();};
  const show=async(c:Certificate,kind:"pdf"|"card")=>{const blob=await fetchPdf(c,kind);setPreview(c);setTab(kind);setPreviewUrl(URL.createObjectURL(blob));};
  const close=()=>{setPreview(null);setPreviewUrl("");};
  const download=async(c:Certificate,kind:"pdf"|"card")=>{const r=await apiFetch(asset(c,kind));if(!r.ok)throw new Error(await r.text());const blob=await r.blob(),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`${c.certificate_number}${kind==="card"?"-card":""}.pdf`;a.click();URL.revokeObjectURL(url);};
  const print=async(c:Certificate,kind:"pdf"|"card")=>{const w=window.open("","_blank");const blob=await fetchPdf(c,kind),url=URL.createObjectURL(blob);if(w){w.location.href=url;w.addEventListener("load",()=>{w.print();setTimeout(()=>URL.revokeObjectURL(url),1000);});}else URL.revokeObjectURL(url);};
  return <section className="px-6 py-10 md:px-10"><p className="text-[0.65rem] uppercase tracking-[0.25em] text-gold">Published Documents</p><h1 className="mt-2 font-serif text-4xl">Certificates</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Published certificate and two-sided gemstone card records. Create and edit source data from Gemstones.</p>
    <div className="mt-7 overflow-hidden rounded-xl border border-border bg-card">{items.length===0?<p className="p-6 text-sm text-muted-foreground">No published certificates yet.</p>:<ul className="divide-y divide-border">{items.map(c=><li key={c.uuid} className="flex flex-wrap items-center justify-between gap-4 p-4"><div><p className="font-medium">{c.certificate_number}</p><p className="mt-1 text-xs text-muted-foreground">{c.gemstone_name} · Issued {c.issued_at?.slice(0,10)} · Version {c.version}</p></div><div className="flex flex-wrap gap-2"><button onClick={()=>void show(c,"pdf")} className="inline-flex items-center gap-1.5 rounded-md border border-border px-3 py-2 text-xs"><Eye/> View</button><button onClick={()=>void download(c,"pdf")} className="inline-flex items-center gap-1.5 rounded-md border border-border px-3 py-2 text-xs"><DownloadSimple/> Certificate</button><button onClick={()=>void download(c,"card")} className="inline-flex items-center gap-1.5 rounded-md border border-border px-3 py-2 text-xs"><DownloadSimple/> Card</button><button onClick={()=>void print(c,"pdf")} className="inline-flex items-center gap-1.5 rounded-md border border-gold bg-gold/10 px-3 py-2 text-xs"><Printer/> Print</button></div></li>)}</ul>}</div>
    {preview&&<div className="fixed inset-0 z-50 flex flex-col bg-black/80 p-4 md:p-8"><div className="mx-auto flex w-full max-w-6xl flex-wrap items-center justify-between gap-3 rounded-t-lg bg-background p-3"><div className="flex gap-2"><button onClick={()=>void show(preview,"pdf")} className={`rounded-md px-4 py-2 text-xs ${tab==="pdf"?"bg-primary text-primary-foreground":"border border-border"}`}>Certificate</button><button onClick={()=>void show(preview,"card")} className={`rounded-md px-4 py-2 text-xs ${tab==="card"?"bg-primary text-primary-foreground":"border border-border"}`}>Card Front & Back</button></div><button onClick={close} className="rounded-md border border-border px-4 py-2 text-xs uppercase">Close</button></div>{previewUrl&&<iframe title={`${preview.certificate_number} preview`} src={previewUrl} className="mx-auto h-full w-full max-w-6xl rounded-b-lg bg-white"/>}</div>}
  </section>;
}
