import * as React from "react";
import { Eye, PencilSimple, Plus, Trash, UploadSimple } from "@phosphor-icons/react";
import { apiFetch, apiJson } from "@/lib/api";
import { allPages } from "@/lib/pagedList";

type TextSizes = Record<string, number | string>;
interface Gem { uuid:string; name_id:string; name_en:string; category:string; gemstone_type:string; gem_code?:string|null; weight_carat:number; color?:string|null; transparency?:string|null; clarity?:string|null; cut?:string|null; shape?:string|null; dimensions_mm?:string|null; origin?:string|null; treatment?:string|null; examiner?:string|null; conclusion?:string|null; presentation_title_size?:number|null; certificate_text_sizes?:Record<string,number>; status:string; certificate_id?:string|null; photo_id?:string|null; }
const EMPTY = { name_en:"", category:"", gemstone_type:"", gem_code:"", weight_carat:"", color:"", transparency:"", clarity:"", cut:"", shape:"", dimensions_mm:"", origin:"", treatment:"", examiner:"", certificate_text_sizes:{} as TextSizes };
const SIZE_LIMITS:Record<string,[number,number]> = { name:[8,22], category:[5,12], species:[5,12], dimensions:[5,12], origin:[5,12], treatment:[5,12] };

export default function GemstonesPage() {
  const [items,setItems]=React.useState<Gem[]>([]), [form,setForm]=React.useState<any>(EMPTY);
  const [editing,setEditing]=React.useState<string|null>(null), [viewing,setViewing]=React.useState<Gem|null>(null);
  const [open,setOpen]=React.useState(false), [busy,setBusy]=React.useState(false), [message,setMessage]=React.useState(""), [q,setQ]=React.useState("");
  const load=React.useCallback(async()=>{const records=await allPages<Gem>(`/api/admin/gemstones?q=${encodeURIComponent(q)}`);setItems(records);},[q]); // eslint-disable-line react-hooks/exhaustive-deps
  React.useEffect(()=>{void load();},[load]);
  const blank=()=>({...EMPTY,certificate_text_sizes:{}});
  const startEdit=(g:Gem)=>{const sizes:TextSizes={...(g.certificate_text_sizes||{})};if(sizes.name==null&&g.presentation_title_size!=null)sizes.name=g.presentation_title_size;setForm({...blank(),...g,weight_carat:String(g.weight_carat),name_en:g.name_en||g.name_id,certificate_text_sizes:sizes});setEditing(g.uuid);setOpen(true);setMessage("");};
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setBusy(true);setMessage("");try{const sizes=Object.fromEntries(Object.entries(form.certificate_text_sizes||{}).filter(([,v])=>v!==""&&v!=null).map(([k,v])=>[k,Number(v)]));const body={...form,name_id:form.name_en,gem_code:form.gem_code.toUpperCase(),weight_carat:Number(form.weight_carat),certificate_text_sizes:sizes,presentation_title_size:sizes.name??null};await apiJson(editing?`/api/admin/gemstones/${editing}`:"/api/admin/gemstones",{method:editing?"PUT":"POST",body:JSON.stringify(body)});setOpen(false);setEditing(null);setForm(blank());setMessage(editing?"Gemstone and certificate text sizes updated.":"Gemstone saved.");await load();}catch(error:any){setMessage(error?.message||"Saving failed.");}finally{setBusy(false);}};
  const uploadPhoto=async(uuid:string,file?:File)=>{if(!file)return;const data=new FormData();data.append("file",file);const r=await apiFetch(`/api/admin/gemstones/${uuid}/photo`,{method:"POST",body:data});if(!r.ok)throw new Error(await r.text());setMessage("Examination photo uploaded.");await load();};
  const publish=async(uuid:string)=>{setBusy(true);setMessage("");try{const r=await apiJson<{certificate_number:string}>(`/api/admin/gemstones/${uuid}/publish`,{method:"POST",body:"{}"});setMessage(`Published as ${r.certificate_number}. Certificate and card are ready.`);await load();}catch(error:any){setMessage(error?.message||"Publishing failed.");}finally{setBusy(false);}};
  const remove=async(g:Gem)=>{if(!window.confirm(`Delete ${g.name_en}?`))return;await apiJson(`/api/admin/gemstones/${g.uuid}`,{method:"DELETE"});await load();};
  const setTextSize=(key:string,value:string)=>setForm((v:any)=>({...v,certificate_text_sizes:{...(v.certificate_text_sizes||{}),[key]:value}}));
  const field=(key:string,label:string,type="text",sizeKey?:string)=>{const limits=sizeKey?SIZE_LIMITS[sizeKey]:undefined;return <label className="block text-xs uppercase tracking-[0.12em] text-muted-foreground">{label}<input required={key!=="treatment"} type={type} step={type==="number"?"0.01":undefined} value={form[key]??""} onChange={e=>setForm((v:any)=>({...v,[key]:e.target.value}))} className="mt-1.5 w-full rounded-md border border-border bg-background px-3 py-2.5 text-sm normal-case tracking-normal text-foreground outline-none focus:border-gold"/>{sizeKey&&limits&&<div className="mt-2 flex items-center gap-2 normal-case tracking-normal"><span className="text-[0.68rem] text-muted-foreground">PDF text size (pt)</span><input type="number" min={limits[0]} max={limits[1]} step="0.5" placeholder="Auto" value={form.certificate_text_sizes?.[sizeKey]??""} onChange={e=>setTextSize(sizeKey,e.target.value)} className="w-24 rounded-md border border-border bg-background px-2 py-1.5 text-xs text-foreground outline-none focus:border-gold"/><span className="text-[0.62rem] text-muted-foreground">blank = auto</span></div>}</label>;};
  return <section className="px-6 py-10 md:px-10">
    <div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-[0.65rem] uppercase tracking-[0.25em] text-gold">Gemstone Records</p><h1 className="mt-2 font-serif text-4xl">Gemstones</h1><p className="mt-2 text-sm text-muted-foreground">The single data source for certificates and gemstone cards.</p></div><button onClick={()=>{setForm(blank());setEditing(null);setOpen(true);}} className="inline-flex items-center gap-2 rounded-md bg-primary px-5 py-3 text-xs uppercase tracking-[0.15em] text-primary-foreground"><Plus/> Add Gemstone</button></div>
    <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search gemstones…" className="mt-6 w-full max-w-md rounded-md border border-border bg-card px-4 py-2.5 text-sm outline-none focus:border-gold"/>
    {message&&<p className="mt-4 rounded-md border border-gold/40 bg-gold/5 px-4 py-3 text-sm">{message}</p>}
    {open&&<form onSubmit={submit} className="mt-6 rounded-xl border border-border bg-card p-6"><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{field("name_en","Gemstone Name","text","name")}{field("category","Category / Variety","text","category")}{field("gemstone_type","Species / Type","text","species")}{field("gem_code","Gemstone Code (3 letters)")}{field("weight_carat","Carat Weight","number")}{field("dimensions_mm","Measurements","text","dimensions")}{field("shape","Shape")}{field("cut","Cut")}{field("color","Colour")}{field("transparency","Transparency")}{field("clarity","Clarity")}{field("origin","Origin","text","origin")}{field("treatment","Treatment (optional)","text","treatment")}{field("examiner","Examiner")}</div><div className="mt-5 flex gap-3"><button disabled={busy} className="rounded-md bg-primary px-5 py-2.5 text-xs uppercase tracking-[0.15em] text-primary-foreground">{busy?"Saving…":"Save Gemstone"}</button><button type="button" onClick={()=>setOpen(false)} className="rounded-md border border-border px-5 py-2.5 text-xs uppercase tracking-[0.15em]">Cancel</button></div></form>}
    <div className="mt-7 overflow-hidden rounded-xl border border-border bg-card">{items.length===0?<p className="p-6 text-sm text-muted-foreground">No gemstone records found.</p>:<ul className="divide-y divide-border">{items.map(g=><li key={g.uuid} className="flex flex-wrap items-center justify-between gap-4 p-4"><div><p className="font-medium">{g.name_en} · {g.weight_carat} ct</p><p className="mt-1 text-xs text-muted-foreground">{g.gemstone_type} · {g.gem_code||"Code required"} · <span className="uppercase">{g.status}</span></p></div><div className="flex flex-wrap items-center gap-2"><label className="inline-flex cursor-pointer items-center gap-1.5 rounded-md border border-border px-3 py-2 text-xs"><UploadSimple/> {g.photo_id?"Replace Photo":"Upload Photo"}<input type="file" accept="image/png,image/jpeg,image/webp" className="hidden" onChange={e=>void uploadPhoto(g.uuid,e.target.files?.[0])}/></label><button onClick={()=>void publish(g.uuid)} disabled={busy} className="rounded-md border border-gold bg-gold/10 px-3 py-2 text-xs font-medium text-primary disabled:opacity-50">Publish</button><button onClick={()=>setViewing(g)} aria-label="View" className="rounded-md border border-border p-2"><Eye/></button><button onClick={()=>startEdit(g)} aria-label="Edit" className="rounded-md border border-border p-2"><PencilSimple/></button><button onClick={()=>void remove(g)} disabled={!!g.certificate_id} aria-label="Delete" className="rounded-md border border-border p-2 text-red-700 disabled:opacity-30"><Trash/></button></div></li>)}</ul>}</div>
    {viewing&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/60 p-4" onClick={()=>setViewing(null)}><div className="w-full max-w-xl rounded-xl bg-background p-6" onClick={e=>e.stopPropagation()}><h2 className="font-serif text-3xl">{viewing.name_en}</h2>{viewing.photo_id&&<div className="mt-4 grid min-h-64 place-items-center rounded-md bg-[linear-gradient(#f5f4f1,#e9e7e2)] p-4"><img src={`/api/gemstone/photo/${viewing.photo_id}`} alt={viewing.name_en} className="max-h-72 max-w-full object-contain"/></div>}<p className="mt-4 text-sm">Status: <span className="capitalize">{viewing.status}</span></p><p className="mt-2 text-sm">Certificate: {viewing.certificate_id||"Not published"}</p><button onClick={()=>setViewing(null)} className="mt-6 rounded-md border border-border px-4 py-2 text-xs uppercase">Close</button></div></div>}
  </section>;
}
